version: '3.8'

services:
  worker-index:
    image: ghcr.io/newitselftools/newsapi/worker-index:latest
    container_name: worker-index
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - SP=${SP}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/gcp/creds.json:ro