services:
  warc:
    image: ghcr.io/newitselftools/newsapi/warc:latest
    container_name: warc
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/gcp/creds.json:ro